training:
  timesteps: 1000000
  report_training: false
  report_denormalized_state: false
  tensorboard_logs: true
hyperparameters:
  learning_rate: 0.0003
  gamma: 0.99
  buffer_size: 1000000
  tau: 0.005
  batch_size: 256
  tensorboard_log: "logs/"
  train_freq: 1
  gradient_steps: 1
