training:
  timesteps: 300000
  report_training: false
  report_denormalized_state: false
  tensorboard_logs: true
hyperparameters:
  learning_rate: 0.00004011012571630973
  gamma: 0.9172823159483275
  buffer_size: 50000
  learning_starts: 4328
  batch_size: 32
  target_update_interval: 5000
  train_freq: 1
  gradient_steps: 1
  exploration_fraction: 0.29309603451086624
  exploration_initial_eps: 1
  exploration_final_eps: 0.04724257286127692
environment_wrapper:
  normalize_state: true
  normalize_reward: false
  normalize_action: false
  continuous_action: false
  discrete_action: true
