training:
  timesteps: 300000
  report_training: false
  report_denormalized_state: false
  tensorboard_logs: true
hyperparameters: {}
environment_wrapper:
  normalize_state: true
  normalize_reward: false
  normalize_action: true
  continuous_action: true
  discrete_action: false
hyperparameter_tuning:
  training_timesteps: 300000
  enabled: true
  num_trials: 20
  num_episodes: 2
  sampler: tpe
