training:
  timesteps: 300000
  report_training: false
  report_denormalized_state: false
  tensorboard_logs: true
hyperparameters:
  ent_coef: "auto_2.0"
  learning_rate: 0.0009851008761417273
  gamma: 0.9305074409820552
  batch_size: 32
environment_wrapper:
  normalize_state: true
  normalize_reward: false
  normalize_action: true
  continuous_action: true
  discrete_action: false
