training:
  timesteps: 300000
  report_training: false
  report_denormalized_state: false
  tensorboard_logs: true
hyperparameters:
  learning_rate: 0.0001
  gamma: 0.99
environment_wrapper:
  normalize_state: true
  normalize_reward: false
  normalize_action: true
  continuous_action: true
  discrete_action: false
hyperparameter_tuning:
  enabled: true
  num_trials: 10
  num_episodes: 1
  sampler: tpe
