training:
  timesteps: 500000
  report_training: false
  report_denormalized_state: false
  tensorboard_logs: true
hyperparameters:
  learning_rate: 0.0003
  gamma: 0.99
  buffer_size: 1000000
  tau: 0.005
  batch_size: 256
  policy_delay: 2
  target_noise_clip: 0.5
  target_policy_noise: 0.2
