training:
  timesteps: 300000
  report_training: false
  report_denormalized_state: false
  tensorboard_logs: true
hyperparameters:
  learning_rate: 0.00037173227725685457
  gamma: 0.9197116803443194
  buffer_size: 200000
  tau: 0.0023821001187396243
  batch_size: 256
  train_freq: 1
  gradient_steps: 8
  policy_delay: 1
  target_policy_noise: 0.20785919458033134
  target_noise_clip: 0.42878779193394845
  device: "cuda"
environment_wrapper:
  normalize_state: true
  normalize_reward: false
  normalize_action: true
  continuous_action: true
  discrete_action: false
