experiments:
  - name: "SAC Experiment"
    engine: "sinergym"
    environment_config: "../rl-building-control/config/environment1.yaml"
    controller: "sac"
    controller_config: "../rl-building-control/config/sac_controller.yaml"
    episodes: 1
    reporting:
      plots: True
      denormalize_state: True
      export: True
  - name: "PPO Experiment"
    engine: "sinergym"
    environment_config: "../rl-building-control/config/environment1.yaml"
    controller: "ppo"
    controller_config: "../rl-building-control/config/ppo_controller.yaml"
    episodes: 1
    reporting:
      plots: True
      denormalize_state: True
      export: True
  - name: "Recurrent PPO Experiment"
    engine: "sinergym"
    environment_config: "../rl-building-control/config/environment1.yaml"
    controller: "recurrent-ppo"
    controller_config: "../rl-building-control/config/recurrent_ppo_controller.yaml"
    episodes: 1
    reporting:
      plots: True
      denormalize_state: True
      export: True
  - name: "A2C Experiment"
    engine: "sinergym"
    environment_config: "../rl-building-control/config/environment1.yaml"
    controller: "a2c"
    controller_config: "../rl-building-control/config/a2c_controller.yaml"
    episodes: 1
    reporting:
      plots: True
      denormalize_state: True
      export: True
  - name: "DDPG Experiment"
    engine: "sinergym"
    environment_config: "../rl-building-control/config/environment1.yaml"
    controller: "ddpg"
    controller_config: "../rl-building-control/config/ddpg_controller.yaml"
    episodes: 1
    reporting:
      plots: True
      denormalize_state: True
      export: True