# Must be available in action space of environment
state_space:
  - air_temp_101
  - humidity_101
  - gas
  - electricity

custom_variables:
  target_temp: 23.0

rules:
  - condition: "air_temp_101 < target_temp"
    action: "[air_temp_101 + 1, 26.5, 23.0]"
  - condition: "air_temp_101 > target_temp"
    action: "[air_temp_101 - 1, 26.5, 23.0]"
  - condition: "True"
    action: "[target_temp, 26.5, 23.0]"