training:
  timesteps: 500_000
  report_training: false
  report_denormalized_state: false

hyperparameter_tuning:
  enabled: false
  num_trials: 50
  num_episodes: 5

hyperparameters:
  learning_rate: 0.0001
  gamma: 0.99
  buffer_size: 10000
  learning_starts: 50000
  batch_size: 32
  target_update_interval: 1000
  exploration_fraction: 0.1
  exploration_final_eps: 0.05
  tensorboard_log: logs/
