building_model: "/home/johannes/workspace/rl-building-control/data/ASHRAE901_HotelSmall_STD2019_Denver.epJSON"
weather_data: "/home/johannes/workspace/rl-building-control/data/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw"

state_space:
  variables:
    air_temp_101:
      type: "Zone Mean Air Temperature"
      zone: "GuestRoom101"
    air_temp_104:
      type: "Zone Mean Air Temperature"
      zone: "GuestRoom104"
    humidity_101:
      type: "Zone Mean Air Humidity Ratio"
      zone: "GuestRoom101"
    outdoor_temp:
      type: "Site Outdoor Air Drybulb Temperature"
      zone: "Environment"
  meters:
    electricity: "Electricity:Facility"
    gas: "NaturalGas:Facility"
  time_info:
    day_of_month:
      cyclic: true
    month:
      cyclic: true
    day_of_week:
      cyclic: true
    hour:
      cyclic: false

action_space:
  actuators:
    setpoint_temp:
      type: "continuous"
      range: [16.0, 28.0]
      component: "Schedule:Constant"
      control_type: "Schedule Value"
      actuator_key: "PythonControlledSetpoint"
    setpoint_temp_2:
      type: "continuous"
      range: [ 16.0, 28.0 ]
      component: "Schedule:Constant"
      control_type: "Schedule Value"
      actuator_key: "PythonControlledSetpoint_2"

reward_function:
  type: "expression"
  variables: ["air_temp_101", "air_temp_104"]
  expression: >
    -1.0 * (
      max(air_temp_101 - max_temp, 0.0)**2 +
      max(min_temp - air_temp_101, 0.0)**2 +
      max(air_temp_104 - max_temp, 0.0)**2 +
      max(min_temp - air_temp_104, 0.0)**2
    )
  params:
    min_temp: 22.0
    max_temp: 24.0

normalize_state: True
