experiments:
  - name: "TD3 experiment"
    engine: "sinergym"
    environment_config: "../rl-building-control/config/environment1.yaml"
    controller: "td3"
    controller_config: "../rl-building-control/config/td3_controller.yaml"
    episodes: 1
    reporting:
      plots: True
      denormalize_state: True
      export: True