experiments:
  - name: "DQN experiment"
    engine: "sinergym"
    environment_config: "../rl-building-control/config/discrete_environment.yaml"
    controller: "dqn"
    controller_config: "../rl-building-control/config/dqn_controller.yaml"
    episodes: 1
    reporting:
      plots: True
      denormalize_state: True
      export: True