training:
 timesteps: 50_000
 report_training: False
 report_denormalized_state: False

hyperparameter_tuning:
 enabled: False
 num_trials: 50
 num_episodes: 5

hyperparameters:
  tensorboard_log: ppo_training_logs/
  learning_rate: 0.00001
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.995
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.001
  vf_coef: 0.5